jobs:
  include:
    # GCC 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - COMPILER="CC=gcc-7 && CXX=g++-7"

    # GCC 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - COMPILER="CC=gcc-8 && CXX=g++-8"

    # GCC 9
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - COMPILER="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${COMPILER}"

dist: focal

language: cpp

compiler:
  - gcc

script:
  - mkdir build && cd build
  - cmake -DBUILD_TESTS=1 ..
  - make -j$(nproc) && bin/unittests
